default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: live_chat_development

test:
  <<: *default
  database: live_chat_test

production:
  primary: &primary_production
    <<: *default
    database: live_chat_production
    username: live_chat
    password: <%= ENV["LIVE_CHAT_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: live_chat_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: live_chat_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: live_chat_production_cable
    migrations_paths: db/cable_migrate
